### ISSUE TITLE
Fuck JSON !

### ISSUE THREAD

**Issue by 4d47** [4d47/install-dependencies#4]
Fuck JSON ! Why not move to a simpler line format (path url checksum)
It would be easier to read, less prone to syntax errors (forgot a comma, etc) and could easily support comments (lines beginning with #)

```
lib/foo http://example.com/foo 39edf3g9c39a949
# a sample comment
lib/bar http://example.com/bar
```

**Comment by khanks** [comment]
Totally agree. It's a POS designed to stimulate searches on stackoverflow which then yield questionable, variable, and downright wrong "answers".
